# This experiment is intende to act as a headless, cli based
# training pipeline intended to acheive results with a model
# trained on the provided dataset.
#
# This experiment will take longer to load because training
# examples are stored in the workstation's RAM. However,
# this may reduce time for examples to be transferred 
# to GPU

experiment:
  __module__: "blocktrain.experiment"
  __class__: "experiment_factory"
  train_dataset:
    __args__: 
      - "/mnt/d/drone_data/training-data"
      - "data/train_indicies.json"
    __module__: "blocktrain.datasets.ir_dataset" 
    __class__: "ir_dataset_factory"
  eval_dataset:
    __args__: 
      - "/mnt/d/drone_data/training-data"
      - "data/eval_indicies.json"
    __module__: "blocktrain.datasets.ir_dataset" 
    __class__: "ir_dataset_factory"
  train_dataloader:
    __module__: "torch.utils.data"
    __class__: "DataLoader"
    batch_size: 2
  eval_dataloader:
    __module__: "torch.utils.data"
    __class__: "DataLoader"
    batch_size: 2
  trainer:
    __module__: "blocktrain.trainer"
    __class__: "Trainer"
    training_input_parameters:
      num_epochs: 2
  callbacks: []
  model:
    __module__: "torchvision.models"
    __class__: "get_model"
    __args__: 
      - "retinanet_resnet50_fpn_v2"
    weights: DEFAULT
  optimizer:
    __module__: "blocktrain.factories.optimizer_factory"
    __class__: "load_optimizer"
    optimizer_module: "torch.optim"
    optimizer_class: "Adam"
    lr: 0.001