experiment:
  __module__: "blocktrain.experiment"
  __class__: "experiment_factory"
  train_dataset:
    __args__: 
      - "/mnt/d/drone_data/training-data"
      - "../data/train_indicies.json"
    __module__: "blocktrain.datasets.ir_dataset" 
    __class__: "ir_dataset_factory"
    child_spec:
      __module__: "blocktrain.datasets.ir_folder_image_file_system_dataset"
      __class__: "FolderImageFileSystemDataset"
  eval_dataset:
    __args__: 
      - "/mnt/d/drone_data/training-data"
      - "../data/eval_indicies.json"
    __module__: "blocktrain.datasets.ir_dataset" 
    __class__: "ir_dataset_factory"
    child_spec:
      __module__: "blocktrain.datasets.ir_folder_image_file_system_dataset"
      __class__: "FolderImageFileSystemDataset"
  trainer:
    __module__: "blocktrain.trainer"
    __class__: "Trainer"
  callbacks: []
  model:
    __module__: "blocktrain.factories.torchvision_model_factory"
    __class__: "load_torchvision_model"
    torchvision_module: "torchvision.models.detection"
    torchvision_class: "retinanet_resnet50_fpn"
    model_kwargs:
      weights: DEFAULT
  optimizer:
    __module__: "blocktrain.factories.optimizer_factory"
    __class__: "load_optimizer"
    optimizer_module: "torch.optim"
    optimizer_class: "Adam"
    lr: 0.001